pipeline {
    agent any

    environment {
        IMAGE_NAME = "omarbaddour1/shelf-check-app"
        TAG = "latest"
        NAMESPACE = "cls"
        DEPLOYMENT_NAME = "shelf-check-app"
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Docker Build") {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:$TAG .
                '''
            }
        }

        stage("Docker Login") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage("Docker Push") {
            steps {
                sh '''
                docker push $IMAGE_NAME:$TAG
                '''
            }
        }

        stage("Deploy to EKS") {
            steps {
                sh '''
                kubectl apply -f K8s/namespace.yaml || true
                kubectl apply -f K8s/serviceaccount.yaml
                kubectl apply -f K8s/alb-sa.yaml
                kubectl apply -f K8s/configmap.yaml
                kubectl apply -f K8s/deployment.yaml
                kubectl apply -f K8s/service.yaml
                kubectl apply -f K8s/ingress.yaml

                kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
                '''
            }
        }
    }
}
