"""add available_copies to book

Revision ID: 37c393cff904
Revises: 4e2b1db485cd
Create Date: 2025-12-14 01:23:01.523839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c393cff904'
down_revision = '4e2b1db485cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_copies', sa.Integer(), nullable=False))

    with op.batch_alter_table('book_copy', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('FK__book_copy__book___412EB0B6'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['book_id'], ondelete='CASCADE')

    with op.batch_alter_table('borrow_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__borrow_tr__copy___440B1D61'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book_copy', ['copy_id'], ['copy_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__borrow_tr__copy___440B1D61'), 'book_copy', ['copy_id'], ['copy_id'])

    with op.batch_alter_table('book_copy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__book_copy__book___412EB0B6'), 'book', ['book_id'], ['book_id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('available_copies')

    # ### end Alembic commands ###
