"""add category to book table

Revision ID: 4e2b1db485cd
Revises: 9d01b3b077ef
Create Date: 2025-11-05 18:34:58.678777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2b1db485cd'
down_revision = '9d01b3b077ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
